### ISSUE TITLE
[Bug] Game Window Size Above 1920 x 1200 Break (De)Buff Icon Clicking

### ISSUE THREAD

**Issue by Guswut** [hamstar0/tml-betterbuffs-mod#1]
#### Steps to reproduce the issue

1.  Open the game window to a resolution larger than 1920 x 1200.
2.  Try and left click a buff icon, or shift left click a buff icon.

#### What's the expected result?

- Left clicking and shift-left clicking would re-apply the buff, or set the buff to automatic re-apply.

#### What's the actual result?

- Nothing appears to happen, no buff items are used, the buff does not get extended, and no dotted rectangle around the buff appears when shift-left clicking.

#### Additional details / screenshot

- Please tell me if I can assist with testing if you cannot replicate it on your system. Thank you!

**Comment by hamstar0** [comment]
Thanks for reporting. Sorry I missed this. Hopefully this should have been solved by now.
